import {
  DatabaseCollectionImplementation,
  DatabaseCollectionSchema,
  DbKey,
} from "../common/DatabaseDefinition";
import { DatabaseFilter } from "../common/DatabaseFilters";
import { DatabaseSortExpression } from "../common/DatabaseSorters";

export default class MongoDbCollection<T>
  implements DatabaseCollectionImplementation<T> {
  
  private schema: DatabaseCollectionSchema;

  getDatabaseName(): string {
    throw new Error("Method not implemented.");
  }
  getDatabaseVersion(): number {
    throw new Error("Method not implemented.");
  }
  getName(): string {
    return this.schema.name;
  }
  getKeyPath(): string | string[] {
    return this.schema.keyPath || "_id";
  }
  isKeyAutoGenerated(): boolean {
    return this.schema.autoGenerated;
  }
  add(record: T): Promise<DbKey> {
    throw new Error("Method not implemented.");
  }
  addBatch(records: T[]): Promise<DbKey[]> {
    throw new Error("Method not implemented.");
  }
  put(record: T): Promise<DbKey> {
    throw new Error("Method not implemented.");
  }
  putBatch(records: T[]): Promise<DbKey[]> {
    throw new Error("Method not implemented.");
  }
  delete(key: DbKey): Promise<unknown> {
    throw new Error("Method not implemented.");
  }
  get(key: DbKey): Promise<T> {
    throw new Error("Method not implemented.");
  }
  all(): Promise<T[]> {
    throw new Error("Method not implemented.");
  }
  filter(fn: (record: T) => boolean): Promise<T[]> {
    throw new Error("Method not implemented.");
  }
  map<G>(fn: (record: T) => any): Promise<G[]> {
    throw new Error("Method not implemented.");
  }
  forEach(fn: (record: T) => void): Promise<unknown> {
    throw new Error("Method not implemented.");
  }
  count(): Promise<number> {
    throw new Error("Method not implemented.");
  }
  query(
    filter: DatabaseFilter,
    sort?: DatabaseSortExpression,
    offset?: number,
    limit?: number
  ): Promise<T[]> {
    throw new Error("Method not implemented.");
  }
}
